#
#--------------------------------------------------------------------------
# Image Setup
#--------------------------------------------------------------------------
#

FROM yifans/php-fpm:main-my-8.1

LABEL maintainer="Yifans_Z <168@yifans.com>"

ARG LARADOCK_PHP_VERSION=8.1

# Set Environment Variables
ENV DEBIAN_FRONTEND noninteractive

ARG CHANGE_SOURCE=false
RUN if [ ${CHANGE_SOURCE} = true ]; then \
    # Change application source from deb.debian.org to aliyun source
    sed -i 's/deb.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
    sed -i 's/security.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list && \
    sed -i 's/security-cdn.debian.org/mirrors.tuna.tsinghua.edu.cn/' /etc/apt/sources.list \
;fi

RUN set -xe; \
    apt-get update -yqq && \
    apt-get install -yqq \
    nginx

WORKDIR /var/www

CMD ["nginx"]

EXPOSE 80 443